/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Prompt {
  'promptText' : string,
  'toolName' : string,
  'stageName' : string,
}
export interface ScriptTemplate {
  'title' : string,
  'twist' : string,
  'body' : string,
  'hook' : string,
  'style' : string,
  'category' : string,
}
export type Time = bigint;
export interface Tool {
  'url' : string,
  'name' : string,
  'description' : string,
  'isFree' : boolean,
  'category' : string,
}
export interface VideoEntry {
  'status' : string,
  'title' : string,
  'date' : Time,
  'platform' : string,
}
export interface WorkflowStage {
  'tools' : Array<string>,
  'name' : string,
  'description' : string,
  'stepNumber' : bigint,
}
export interface _SERVICE {
  'addVideoEntry' : ActorMethod<[string, string, string, Time], undefined>,
  'deleteVideoEntry' : ActorMethod<[Time], undefined>,
  'getAllVideoEntries' : ActorMethod<[], Array<VideoEntry>>,
  'getPrompts' : ActorMethod<[], Array<Prompt>>,
  'getScriptTemplates' : ActorMethod<[], Array<ScriptTemplate>>,
  'getTools' : ActorMethod<[], Array<Tool>>,
  'getVideoEntry' : ActorMethod<[Time], VideoEntry>,
  'getWorkflowStages' : ActorMethod<[], Array<WorkflowStage>>,
  'updateVideoEntry' : ActorMethod<[Time, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];