/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const VideoEntry = IDL.Record({
  'status' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'platform' : IDL.Text,
});
export const Prompt = IDL.Record({
  'promptText' : IDL.Text,
  'toolName' : IDL.Text,
  'stageName' : IDL.Text,
});
export const ScriptTemplate = IDL.Record({
  'title' : IDL.Text,
  'twist' : IDL.Text,
  'body' : IDL.Text,
  'hook' : IDL.Text,
  'style' : IDL.Text,
  'category' : IDL.Text,
});
export const Tool = IDL.Record({
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFree' : IDL.Bool,
  'category' : IDL.Text,
});
export const WorkflowStage = IDL.Record({
  'tools' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addVideoEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
  'deleteVideoEntry' : IDL.Func([Time], [], []),
  'getAllVideoEntries' : IDL.Func([], [IDL.Vec(VideoEntry)], ['query']),
  'getPrompts' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
  'getScriptTemplates' : IDL.Func([], [IDL.Vec(ScriptTemplate)], ['query']),
  'getTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getVideoEntry' : IDL.Func([Time], [VideoEntry], ['query']),
  'getWorkflowStages' : IDL.Func([], [IDL.Vec(WorkflowStage)], ['query']),
  'updateVideoEntry' : IDL.Func([Time, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const VideoEntry = IDL.Record({
    'status' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'platform' : IDL.Text,
  });
  const Prompt = IDL.Record({
    'promptText' : IDL.Text,
    'toolName' : IDL.Text,
    'stageName' : IDL.Text,
  });
  const ScriptTemplate = IDL.Record({
    'title' : IDL.Text,
    'twist' : IDL.Text,
    'body' : IDL.Text,
    'hook' : IDL.Text,
    'style' : IDL.Text,
    'category' : IDL.Text,
  });
  const Tool = IDL.Record({
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFree' : IDL.Bool,
    'category' : IDL.Text,
  });
  const WorkflowStage = IDL.Record({
    'tools' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
  });
  
  return IDL.Service({
    'addVideoEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
    'deleteVideoEntry' : IDL.Func([Time], [], []),
    'getAllVideoEntries' : IDL.Func([], [IDL.Vec(VideoEntry)], ['query']),
    'getPrompts' : IDL.Func([], [IDL.Vec(Prompt)], ['query']),
    'getScriptTemplates' : IDL.Func([], [IDL.Vec(ScriptTemplate)], ['query']),
    'getTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getVideoEntry' : IDL.Func([Time], [VideoEntry], ['query']),
    'getWorkflowStages' : IDL.Func([], [IDL.Vec(WorkflowStage)], ['query']),
    'updateVideoEntry' : IDL.Func([Time, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };