/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScriptTemplate {
    title: string;
    twist: string;
    body: string;
    hook: string;
    style: string;
    category: string;
}
export interface Tool {
    url: string;
    name: string;
    description: string;
    isFree: boolean;
    category: string;
}
export type Time = bigint;
export interface Prompt {
    promptText: string;
    toolName: string;
    stageName: string;
}
export interface VideoEntry {
    status: string;
    title: string;
    date: Time;
    platform: string;
}
export interface WorkflowStage {
    tools: Array<string>;
    name: string;
    description: string;
    stepNumber: bigint;
}
export interface backendInterface {
    addVideoEntry(title: string, platform: string, status: string, date: Time): Promise<void>;
    deleteVideoEntry(date: Time): Promise<void>;
    getAllVideoEntries(): Promise<Array<VideoEntry>>;
    getPrompts(): Promise<Array<Prompt>>;
    getScriptTemplates(): Promise<Array<ScriptTemplate>>;
    getTools(): Promise<Array<Tool>>;
    getVideoEntry(date: Time): Promise<VideoEntry>;
    getWorkflowStages(): Promise<Array<WorkflowStage>>;
    updateVideoEntry(date: Time, title: string, platform: string, status: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addVideoEntry(arg0: string, arg1: string, arg2: string, arg3: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteVideoEntry(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoEntry(arg0);
            return result;
        }
    }
    async getAllVideoEntries(): Promise<Array<VideoEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVideoEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVideoEntries();
            return result;
        }
    }
    async getPrompts(): Promise<Array<Prompt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrompts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrompts();
            return result;
        }
    }
    async getScriptTemplates(): Promise<Array<ScriptTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptTemplates();
            return result;
        }
    }
    async getTools(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTools();
            return result;
        }
    }
    async getVideoEntry(arg0: Time): Promise<VideoEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideoEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideoEntry(arg0);
            return result;
        }
    }
    async getWorkflowStages(): Promise<Array<WorkflowStage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkflowStages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkflowStages();
            return result;
        }
    }
    async updateVideoEntry(arg0: Time, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
